name: ipconfig

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
